### ISSUE TITLE
if(conditie) return true } else {return false} poate fi inlocuit cu return conditie

### ISSUE THREAD

**Issue by stefanbulzan** [AdrianBuzamat/curs7-homework#1]
https://github.com/AdrianBuzamat/curs7-homework/blob/a0bcfa2ff5aa2a7bdfc0d6a372cf0cc1a7f62485/src/ro/fasttrackit/curs7/Product.java#L31

**Comment by AdrianBuzamat** [comment]
Am implementat comentariul.
